services:
  app:
    build:
      context: .
      args:
      - DEV=true
    restart: always
    environment:
      - FLASK_APP=app.main
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/venv
    command: flask run --host=0.0.0.0 --port=8000 --reload

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"

volumes:
  postgres-data:
