swagger: "2.0"
info:
  title: "Article API"
  description: "API for managing a articles"
  version: "1.0.0"
host: "127.0.0.1:8000"
basePath: "/"
schemes:
  - "http"

paths:
  /articles:
    get:
      summary: "Retrieve all articles"
      responses:
        200:
          description: "A list of all articles"
          content:
            application/json:
              example:
                books:
                  - id: 1
                    author_id: 1
                    title: "My First Article"
                    description: "This is the description of my first article."
                    body: "Here is the full body of my first article. It can contain multiple paragraphs and other content"
                  - id: 2
                    author_id: 1
                    title: "My Second Article"
                    description: "This is the description of my second article."
                    body: "Here is the full body of my second article. It can contain multiple paragraphs and other content"
    post:
      summary: "Add a new article"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                author_id:
                  type: number
                title:
                  type: string
                description:
                  type: string
                body:
                  type: string
              example:
                author_id: 1
                title: "The new article"
                description: "The new article description"
                body: "The new article body"
      responses:
        201:
          description: "The newly added article"
          content:
            application/json:
              example:
                id: 1
                author_id: 1
                title: "The new article"
                description: "The new article description"
                body: "The new article body"

  /articles/{article_id}:
    get:
      summary: "Retrieve a specific article by ID"
      parameters:
        - name: "article_id"
          in: "path"
          required: true
          type: "integer"
          description: "ID of the article to retrieve"
      responses:
        200:
          description: "Details of the specified article"
          content:
            application/json:
              example:
                id: 1
                author_id: 1
                title: "The new article"
                description: "The new article description"
                body: "The new article body"
        404:
          description: "Article not found"
    put:
      summary: "Update an existing article"
      parameters:
        - name: "article_id"
          in: "path"
          required: true
          type: "integer"
          description: "ID of the article to update"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                author_id:
                  type: number
                title:
                  type: string
                description:
                  type: string
                body:
                  type: string
      responses:
        200:
          description: "The updated article information"
          content:
            application/json:
              example:
                id: 1
                author_id: 1
                title: "The new article"
                description: "The new article description"
                body: "The new article body"
        404:
          description: "Article not found"
    delete:
      summary: "Delete a article"
      parameters:
        - name: "article_id"
          in: "path"
          required: true
          type: "integer"
          description: "ID of the article to delete"
      responses:
        200:
          description: "Article deletion confirmation"
          content:
            application/json:
              example:
                message: "Article deleted successfully"
        404:
          description: "Article not found"
