name: Build Docker Images

on:
  workflow_call:
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        run: |
          docker compose build
          docker compose push
