name: CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: test-and-lint

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: build
    with:
        WORK_APP_DIR: ${{ vars.WORK_APP_DIR }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_USER: ${{ vars.DB_USER }}
    secrets:
        VM_HOST: ${{ secrets.VM_HOST }}
        VM_USERNAME: ${{ secrets.VM_USERNAME }}
        VM_PRIVATE_KEY: ${{ secrets.VM_PRIVATE_KEY }}
        VM_PORT: ${{ secrets.VM_PORT }}
        DB_PASS: ${{ secrets.DB_PASS }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}