name: Test and Lint

on:
  workflow_call:
jobs:
  python:
    name: Python
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Unit Tests
        run: docker compose run --rm app sh -c "pytest"

      - name: Run Flake8 Linter
        run: docker compose run --rm app sh -c "flake8"
